version: "3"

volumes:
  postgres_data: {}

services:
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./reports-ws/.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command: -p 5432

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./reports-react-web/build:/usr/share/nginx/html

  ws:
    image: reports-ws
    build: ./reports-ws/
    env_file:
      - ./reports-ws/.env
    ports:
      - "5000:5000"
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./reports-ws/:/app
    command: sh /app/deploy.sh